package ru.skillbranch.devintensive

import compareEquals
import org.junit.Test
import ru.skillbranch.devintensive.extensions.TimeUnits

class Task10 {

    @Test
    fun `Задание 10, проверка секунд`() {
        compareEquals(TimeUnits.SECOND.plural(0), "0 секунд")
        compareEquals(TimeUnits.SECOND.plural(1), "1 секунду")
        compareEquals(TimeUnits.SECOND.plural(2), "2 секунды")
        compareEquals(TimeUnits.SECOND.plural(4), "4 секунды")
        compareEquals(TimeUnits.SECOND.plural(5), "5 секунд")
        compareEquals(TimeUnits.SECOND.plural(7), "7 секунд")
        compareEquals(TimeUnits.SECOND.plural(10), "10 секунд")
        compareEquals(TimeUnits.SECOND.plural(11), "11 секунд")
        compareEquals(TimeUnits.SECOND.plural(12), "12 секунд")
        compareEquals(TimeUnits.SECOND.plural(13), "13 секунд")
        compareEquals(TimeUnits.SECOND.plural(14), "14 секунд")
        compareEquals(TimeUnits.SECOND.plural(21), "21 секунду")
        compareEquals(TimeUnits.SECOND.plural(22), "22 секунды")
        compareEquals(TimeUnits.SECOND.plural(24), "24 секунды")
        compareEquals(TimeUnits.SECOND.plural(25), "25 секунд")
        compareEquals(TimeUnits.SECOND.plural(30), "30 секунд")
        compareEquals(TimeUnits.SECOND.plural(31), "31 секунду")
        compareEquals(TimeUnits.SECOND.plural(32), "32 секунды")
        compareEquals(TimeUnits.SECOND.plural(35), "35 секунд")
        compareEquals(TimeUnits.SECOND.plural(100), "100 секунд")
        compareEquals(TimeUnits.SECOND.plural(101), "101 секунду")
        compareEquals(TimeUnits.SECOND.plural(102), "102 секунды")
        compareEquals(TimeUnits.SECOND.plural(105), "105 секунд")
        compareEquals(TimeUnits.SECOND.plural(111), "111 секунд")
        compareEquals(TimeUnits.SECOND.plural(112), "112 секунд")
        compareEquals(TimeUnits.SECOND.plural(114), "114 секунд")
        compareEquals(TimeUnits.SECOND.plural(121), "121 секунду")
        compareEquals(TimeUnits.SECOND.plural(122), "122 секунды")
        compareEquals(TimeUnits.SECOND.plural(125), "125 секунд")
        compareEquals(TimeUnits.SECOND.plural(130), "130 секунд")
        compareEquals(TimeUnits.SECOND.plural(131), "131 секунду")
        compareEquals(TimeUnits.SECOND.plural(1000), "1000 секунд")
        compareEquals(TimeUnits.SECOND.plural(1001), "1001 секунду")
        compareEquals(TimeUnits.SECOND.plural(1002), "1002 секунды")
        compareEquals(TimeUnits.SECOND.plural(1004), "1004 секунды")
        compareEquals(TimeUnits.SECOND.plural(1005), "1005 секунд")
        compareEquals(TimeUnits.SECOND.plural(1011), "1011 секунд")
        compareEquals(TimeUnits.SECOND.plural(1234), "1234 секунды")
    }

    @Test
    fun `Задание 10, проверка минут`() {
        compareEquals(TimeUnits.MINUTE.plural(0), "0 минут")
        compareEquals(TimeUnits.MINUTE.plural(1), "1 минуту")
        compareEquals(TimeUnits.MINUTE.plural(2), "2 минуты")
        compareEquals(TimeUnits.MINUTE.plural(4), "4 минуты")
        compareEquals(TimeUnits.MINUTE.plural(5), "5 минут")
        compareEquals(TimeUnits.MINUTE.plural(7), "7 минут")
        compareEquals(TimeUnits.MINUTE.plural(10), "10 минут")
        compareEquals(TimeUnits.MINUTE.plural(11), "11 минут")
        compareEquals(TimeUnits.MINUTE.plural(12), "12 минут")
        compareEquals(TimeUnits.MINUTE.plural(13), "13 минут")
        compareEquals(TimeUnits.MINUTE.plural(14), "14 минут")
        compareEquals(TimeUnits.MINUTE.plural(21), "21 минуту")
        compareEquals(TimeUnits.MINUTE.plural(22), "22 минуты")
        compareEquals(TimeUnits.MINUTE.plural(24), "24 минуты")
        compareEquals(TimeUnits.MINUTE.plural(25), "25 минут")
        compareEquals(TimeUnits.MINUTE.plural(30), "30 минут")
        compareEquals(TimeUnits.MINUTE.plural(31), "31 минуту")
        compareEquals(TimeUnits.MINUTE.plural(32), "32 минуты")
        compareEquals(TimeUnits.MINUTE.plural(35), "35 минут")
        compareEquals(TimeUnits.MINUTE.plural(100), "100 минут")
        compareEquals(TimeUnits.MINUTE.plural(101), "101 минуту")
        compareEquals(TimeUnits.MINUTE.plural(102), "102 минуты")
        compareEquals(TimeUnits.MINUTE.plural(105), "105 минут")
        compareEquals(TimeUnits.MINUTE.plural(111), "111 минут")
        compareEquals(TimeUnits.MINUTE.plural(112), "112 минут")
        compareEquals(TimeUnits.MINUTE.plural(114), "114 минут")
        compareEquals(TimeUnits.MINUTE.plural(121), "121 минуту")
        compareEquals(TimeUnits.MINUTE.plural(122), "122 минуты")
        compareEquals(TimeUnits.MINUTE.plural(125), "125 минут")
        compareEquals(TimeUnits.MINUTE.plural(130), "130 минут")
        compareEquals(TimeUnits.MINUTE.plural(131), "131 минуту")
        compareEquals(TimeUnits.MINUTE.plural(1000), "1000 минут")
        compareEquals(TimeUnits.MINUTE.plural(1001), "1001 минуту")
        compareEquals(TimeUnits.MINUTE.plural(1002), "1002 минуты")
        compareEquals(TimeUnits.MINUTE.plural(1004), "1004 минуты")
        compareEquals(TimeUnits.MINUTE.plural(1005), "1005 минут")
        compareEquals(TimeUnits.MINUTE.plural(1011), "1011 минут")
        compareEquals(TimeUnits.MINUTE.plural(1234), "1234 минуты")
    }

    @Test
    fun `Задание 10, проверка часов`() {
        compareEquals(TimeUnits.HOUR.plural(0), "0 часов")
        compareEquals(TimeUnits.HOUR.plural(1), "1 час")
        compareEquals(TimeUnits.HOUR.plural(2), "2 часа")
        compareEquals(TimeUnits.HOUR.plural(4), "4 часа")
        compareEquals(TimeUnits.HOUR.plural(5), "5 часов")
        compareEquals(TimeUnits.HOUR.plural(7), "7 часов")
        compareEquals(TimeUnits.HOUR.plural(10), "10 часов")
        compareEquals(TimeUnits.HOUR.plural(11), "11 часов")
        compareEquals(TimeUnits.HOUR.plural(12), "12 часов")
        compareEquals(TimeUnits.HOUR.plural(13), "13 часов")
        compareEquals(TimeUnits.HOUR.plural(14), "14 часов")
        compareEquals(TimeUnits.HOUR.plural(21), "21 час")
        compareEquals(TimeUnits.HOUR.plural(22), "22 часа")
        compareEquals(TimeUnits.HOUR.plural(24), "24 часа")
        compareEquals(TimeUnits.HOUR.plural(25), "25 часов")
        compareEquals(TimeUnits.HOUR.plural(30), "30 часов")
        compareEquals(TimeUnits.HOUR.plural(31), "31 час")
        compareEquals(TimeUnits.HOUR.plural(32), "32 часа")
        compareEquals(TimeUnits.HOUR.plural(35), "35 часов")
        compareEquals(TimeUnits.HOUR.plural(100), "100 часов")
        compareEquals(TimeUnits.HOUR.plural(101), "101 час")
        compareEquals(TimeUnits.HOUR.plural(102), "102 часа")
        compareEquals(TimeUnits.HOUR.plural(105), "105 часов")
        compareEquals(TimeUnits.HOUR.plural(111), "111 часов")
        compareEquals(TimeUnits.HOUR.plural(112), "112 часов")
        compareEquals(TimeUnits.HOUR.plural(114), "114 часов")
        compareEquals(TimeUnits.HOUR.plural(121), "121 час")
        compareEquals(TimeUnits.HOUR.plural(122), "122 часа")
        compareEquals(TimeUnits.HOUR.plural(125), "125 часов")
        compareEquals(TimeUnits.HOUR.plural(130), "130 часов")
        compareEquals(TimeUnits.HOUR.plural(131), "131 час")
        compareEquals(TimeUnits.HOUR.plural(1000), "1000 часов")
        compareEquals(TimeUnits.HOUR.plural(1001), "1001 час")
        compareEquals(TimeUnits.HOUR.plural(1002), "1002 часа")
        compareEquals(TimeUnits.HOUR.plural(1004), "1004 часа")
        compareEquals(TimeUnits.HOUR.plural(1005), "1005 часов")
        compareEquals(TimeUnits.HOUR.plural(1011), "1011 часов")
        compareEquals(TimeUnits.HOUR.plural(1234), "1234 часа")
    }


    @Test
    fun `Задание 10, проверка дней`() {
        compareEquals(TimeUnits.DAY.plural(0), "0 дней")
        compareEquals(TimeUnits.DAY.plural(1), "1 день")
        compareEquals(TimeUnits.DAY.plural(2), "2 дня")
        compareEquals(TimeUnits.DAY.plural(4), "4 дня")
        compareEquals(TimeUnits.DAY.plural(5), "5 дней")
        compareEquals(TimeUnits.DAY.plural(7), "7 дней")
        compareEquals(TimeUnits.DAY.plural(10), "10 дней")
        compareEquals(TimeUnits.DAY.plural(11), "11 дней")
        compareEquals(TimeUnits.DAY.plural(12), "12 дней")
        compareEquals(TimeUnits.DAY.plural(13), "13 дней")
        compareEquals(TimeUnits.DAY.plural(14), "14 дней")
        compareEquals(TimeUnits.DAY.plural(21), "21 день")
        compareEquals(TimeUnits.DAY.plural(22), "22 дня")
        compareEquals(TimeUnits.DAY.plural(24), "24 дня")
        compareEquals(TimeUnits.DAY.plural(25), "25 дней")
        compareEquals(TimeUnits.DAY.plural(30), "30 дней")
        compareEquals(TimeUnits.DAY.plural(31), "31 день")
        compareEquals(TimeUnits.DAY.plural(32), "32 дня")
        compareEquals(TimeUnits.DAY.plural(35), "35 дней")
        compareEquals(TimeUnits.DAY.plural(100), "100 дней")
        compareEquals(TimeUnits.DAY.plural(101), "101 день")
        compareEquals(TimeUnits.DAY.plural(102), "102 дня")
        compareEquals(TimeUnits.DAY.plural(105), "105 дней")
        compareEquals(TimeUnits.DAY.plural(111), "111 дней")
        compareEquals(TimeUnits.DAY.plural(112), "112 дней")
        compareEquals(TimeUnits.DAY.plural(114), "114 дней")
        compareEquals(TimeUnits.DAY.plural(121), "121 день")
        compareEquals(TimeUnits.DAY.plural(122), "122 дня")
        compareEquals(TimeUnits.DAY.plural(125), "125 дней")
        compareEquals(TimeUnits.DAY.plural(130), "130 дней")
        compareEquals(TimeUnits.DAY.plural(131), "131 день")
        compareEquals(TimeUnits.DAY.plural(1000), "1000 дней")
        compareEquals(TimeUnits.DAY.plural(1001), "1001 день")
        compareEquals(TimeUnits.DAY.plural(1002), "1002 дня")
        compareEquals(TimeUnits.DAY.plural(1004), "1004 дня")
        compareEquals(TimeUnits.DAY.plural(1005), "1005 дней")
        compareEquals(TimeUnits.DAY.plural(1011), "1011 дней")
        compareEquals(TimeUnits.DAY.plural(1234), "1234 дня")
    }
}